acl "test1" {
  1.1.1.1;
  !{key "abc";};
};
zone "example.com" In { type master; file "example.comx";};

controls {
    inet * port 53 allow {2.2.2.2;} keys { 1;} read-only true;
};

key 1 {
    algorithm hmac-sha1;
    secret SGVsbG8gd29ybGQ=;
};

